<?php

use Illuminate\Database\Seeder;

class AdminsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::table('admins')->truncate();
        DB::table('admins')->insert([
            [
                'first_name' => '健太',
                'last_name' => '山本',
                'first_name_kana' => 'ケンタ',
                'last_name_kana' => 'ヤマモト',
                'gender' => 1,
                'email' => 'admin@itpropartners.jp',
                'password' => bcrypt('admin'),
                'avatar_path' => 'admins/1/avatar_path/XjK9ZxhOwvaonaZ7UVScdPx14FPKu4pKn285v6mM.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '慎一郎',
                'last_name' => '村田',
                'first_name_kana' => 'シンイチロウ',
                'last_name_kana' => 'ムラタ',
                'gender' => 1,
                'email' => 'admin2@itpropartners.jp',
                'password' => bcrypt('admin2'),
                'avatar_path' => 'admins/2/avatar_path/epBNyXtCH3JxtHPn3q3FpCFvPf33lM3j15waRXJr.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '悟',
                'last_name' => '前田',
                'first_name_kana' => 'サトル',
                'last_name_kana' => 'マエダ',
                'gender' => 1,
                'email' => 'admin3@itpropartners.jp',
                'password' => bcrypt('admin3'),
                'avatar_path' => 'admins/3/avatar_path/Pn9quvoLQmWyQTIJiXzWdyPAwPsD2UTjQ68NxjtN.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '誠',
                'last_name' => '大竹',
                'first_name_kana' => 'マコト',
                'last_name_kana' => 'オオタケ',
                'gender' => 1,
                'email' => 'admin4@itpropartners.jp',
                'password' => bcrypt('admin4'),
                'avatar_path' => 'admins/4/avatar_path/rXCeLvjYNYfugPOen6MPVBi1tXlgxxC4GHOH1mKL.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '翔太',
                'last_name' => '梅田',
                'first_name_kana' => 'ショウタ',
                'last_name_kana' => 'ウメダ',
                'gender' => 1,
                'email' => 'admin5@itpropartners.jp',
                'password' => bcrypt('admin5'),
                'avatar_path' => 'admins/5/avatar_path/TVhCouoj66ifCIuIFcfLSlwtYIDfi4iwjWg8LUem.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '俊平',
                'last_name' => '菅野',
                'first_name_kana' => 'シュンペイ',
                'last_name_kana' => 'スガノ',
                'gender' => 1,
                'email' => 'admin6@itpropartners.jp',
                'password' => bcrypt('admin6'),
                'avatar_path' => 'admins/6/avatar_path/gCeRkLv31PGfgvp2DOVUT4ASblJCJfabm0KhG4ai.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '和樹',
                'last_name' => '小栗',
                'first_name_kana' => 'カズキ',
                'last_name_kana' => 'オグリ',
                'gender' => 1,
                'email' => 'admin7@itpropartners.jp',
                'password' => bcrypt('admin7'),
                'avatar_path' => 'admins/7/avatar_path/4SgZQfoWJYv9bOEGUtc1V0OYG9z0WBnoS1eM2Kgv.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '優馬',
                'last_name' => '櫻井',
                'first_name_kana' => 'ユウマ',
                'last_name_kana' => 'サクライ',
                'gender' => 1,
                'email' => 'admin8@itpropartners.jp',
                'password' => bcrypt('admin8'),
                'avatar_path' => 'admins/8/avatar_path/haPSZ3fatRnwdeJhufWwsErhZN6ZloNWIHGa1olg.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '優里',
                'last_name' => '長尾',
                'first_name_kana' => 'ユリ',
                'last_name_kana' => 'ナガオ',
                'gender' => 2,
                'email' => 'admin9@itpropartners.jp',
                'password' => bcrypt('admin9'),
                'avatar_path' => 'admins/9/avatar_path/54bxL6VzmzFLPS7T8ermkHubmeClSUsfqaxI418D.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '明',
                'last_name' => '岩田',
                'first_name_kana' => 'アカリ',
                'last_name_kana' => 'イワタ',
                'gender' => 2,
                'email' => 'admin10@itpropartners.jp',
                'password' => bcrypt('admin10'),
                'avatar_path' => 'admins/10/avatar_path/jFzRTIiAPDi6xAZEwLLqxUC27z1j3ewXmYNOeFaH.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '奈緒',
                'last_name' => '堤',
                'first_name_kana' => 'ナオ',
                'last_name_kana' => 'ツツミ',
                'gender' => 2,
                'email' => 'admin11@itpropartners.jp',
                'password' => bcrypt('admin11'),
                'avatar_path' => 'admins/11/avatar_path/HyDPZGA2IzXu05vHOUYXWLFNFgs98dM1Y9gysVnl.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '結',
                'last_name' => '斎藤',
                'first_name_kana' => 'ユイ',
                'last_name_kana' => 'サイトウ',
                'gender' => 2,
                'email' => 'admin12@itpropartners.jp',
                'password' => bcrypt('admin12'),
                'avatar_path' => 'admins/12/avatar_path/7gIWF9P3dFpLznjVr2HuRBjz4ZV0KJoeAwvzEn4s.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '春菜',
                'last_name' => '渡辺',
                'first_name_kana' => 'ハルナ',
                'last_name_kana' => 'ワタナベ',
                'gender' => 2,
                'email' => 'admin13@itpropartners.jp',
                'password' => bcrypt('admin13'),
                'avatar_path' => 'admins/13/avatar_path/QiEk5sGCgVog4BtKvS1WwDEU9HRFFQNo610KcfnO.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '恵',
                'last_name' => '安藤',
                'first_name_kana' => 'メグミ',
                'last_name_kana' => 'アンドウ',
                'gender' => 2,
                'email' => 'admin14@itpropartners.jp',
                'password' => bcrypt('admin14'),
                'avatar_path' => 'admins/14/avatar_path/xNIdbPCPOBYaQPtzhI43pL28h0SYZRvMdqZbFAyh.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '由真',
                'last_name' => '松浦',
                'first_name_kana' => 'ユマ',
                'last_name_kana' => 'マツウラ',
                'gender' => 2,
                'email' => 'admin15@itpropartners.jp',
                'password' => bcrypt('admin15'),
                'avatar_path' => 'admins/15/avatar_path/t5s02SpIqwqHncFdHAJHEReQME25mjfFh7MJwmp1.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
