<?php

use Illuminate\Database\Seeder;

class ClientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::table('clients')->truncate();
        DB::table('clients')->insert([
            [
                'company_id' => '1',
                'first_name' => '幸田',
                'last_name' => '内藤',
                'first_name_kana' => 'コウタ',
                'last_name_kana' => 'ナイトウ',
                'gender' => 1,
                'email' => 'companyuser+1@itpropartners.jp',
                'password' => bcrypt('admin'),
                'avatar_path' => 'clients/1/avatar_path/LsQk4CLRi7ytjAhoDqAM9xTgoo9T8LQbSRp6BOQR.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '2',
                'first_name' => '周平',
                'last_name' => '和田',
                'first_name_kana' => 'シュウヘイ',
                'last_name_kana' => 'ワダ',
                'gender' => 1,
                'email' => 'companyuser+2@itpropartners.jp',
                'password' => bcrypt('admin2'),
                'avatar_path' => 'clients/2/avatar_path/6wOYHTabadRjNyVXaEHG39jYfjHcVWizNPt9xl4p.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '3',
                'first_name' => '勇気',
                'last_name' => '野村',
                'first_name_kana' => 'ユウキ',
                'last_name_kana' => 'ノムラ',
                'gender' => 1,
                'email' => 'companyuser+3@itpropartners.jp',
                'password' => bcrypt('admin3'),
                'avatar_path' => 'clients/3/avatar_path/0E7FtYppbbJUfY7rPywHpADLb5ze0NRZMIemI01M.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '4',
                'first_name' => '智樹',
                'last_name' => '松本',
                'first_name_kana' => 'トモキ',
                'last_name_kana' => 'マツモト',
                'gender' => 1,
                'email' => 'companyuser+4@itpropartners.jp',
                'password' => bcrypt('admin4'),
                'avatar_path' => 'clients/4/avatar_path/7L7ZViEnhM4Nf2szhJZ6pGBtHv236qEH4GlAKdSw.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '5',
                'first_name' => '和正',
                'last_name' => '高橋',
                'first_name_kana' => 'カズマサ',
                'last_name_kana' => 'タカハシ',
                'gender' => 1,
                'email' => 'companyuser+5@itpropartners.jp',
                'password' => bcrypt('admin5'),
                'avatar_path' => 'clients/5/avatar_path/7OOASPrzVY9lFB86joCjghARSgIJPep7d17dLIKV.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '6',
                'first_name' => '祐介',
                'last_name' => '遠藤',
                'first_name_kana' => 'ユウスケ',
                'last_name_kana' => 'エンドウ',
                'gender' => 1,
                'email' => 'companyuser+6@itpropartners.jp',
                'password' => bcrypt('admin6'),
                'avatar_path' => 'clients/6/avatar_path/vnoF7WLhulkyRE14lS6KbzGedtnWCmoubLvWVnL5.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '7',
                'first_name' => '良太',
                'last_name' => '宮城',
                'first_name_kana' => 'リョウタ',
                'last_name_kana' => 'ミヤギ',
                'gender' => 1,
                'email' => 'companyuser+7@itpropartners.jp',
                'password' => bcrypt('admin7'),
                'avatar_path' => 'clients/7/avatar_path/f96PttIzEPuNS1A71aQXYsywVVEIPZx4HZRfahKZ.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '8',
                'first_name' => '正',
                'last_name' => '河合',
                'first_name_kana' => 'タダシ',
                'last_name_kana' => 'カワイ',
                'gender' => 1,
                'email' => 'companyuser+8@itpropartners.jp',
                'password' => bcrypt('admin8'),
                'avatar_path' => 'clients/8/avatar_path/azU2mtYIdYPxFaAeRFYwV5bv5RQ4iLEjYcOntF9E.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '9',
                'first_name' => '真奈',
                'last_name' => '桐山',
                'first_name_kana' => 'マナ',
                'last_name_kana' => 'キリヤマ',
                'gender' => 2,
                'email' => 'companyuser+9@itpropartners.jp',
                'password' => bcrypt('admin9'),
                'avatar_path' => 'clients/9/avatar_path/JVSaDG2WXH4Xd7lc3oFBKaqmd797unkLbCkgp5ws.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '10',
                'first_name' => '由佳',
                'last_name' => '大橋',
                'first_name_kana' => 'ユカ',
                'last_name_kana' => 'オオハシ',
                'gender' => 2,
                'email' => 'companyuser+10@itpropartners.jp',
                'password' => bcrypt('admin10'),
                'avatar_path' => 'clients/10/avatar_path/xfIvqjx5TW351U8KBd2fPL7owbcoalZylNjs8RBk.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '11',
                'first_name' => '菜々',
                'last_name' => '小林',
                'first_name_kana' => 'ナナ',
                'last_name_kana' => 'コバヤシ',
                'gender' => 2,
                'email' => 'companyuser+11@itpropartners.jp',
                'password' => bcrypt('admin11'),
                'avatar_path' => 'clients/11/avatar_path/YGX3sem5qB5C9i54slR5OgXlZZUWCH425clUKV8Q.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '1',
                'first_name' => '早紀',
                'last_name' => '大塚',
                'first_name_kana' => 'サキ',
                'last_name_kana' => 'オオツカ',
                'gender' => 2,
                'email' => 'companyuser+12@itpropartners.jp',
                'password' => bcrypt('admin12'),
                'avatar_path' => 'clients/12/avatar_path/wVmVzcm6UZ9VKYFAAFmEXDlx2tZnzcIO8qBgTZ6o.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '2',
                'first_name' => '未来',
                'last_name' => '武藤',
                'first_name_kana' => 'ミク',
                'last_name_kana' => 'ムトウ',
                'gender' => 2,
                'email' => 'companyuser+13@itpropartners.jp',
                'password' => bcrypt('admin13'),
                'avatar_path' => 'clients/13/avatar_path/wjuAcu28sfWjDEQqmyccyYvHYfsrDot3wmB01XTM.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '3',
                'first_name' => '比奈',
                'last_name' => '西田',
                'first_name_kana' => 'ヒナ',
                'last_name_kana' => 'ニシダ',
                'gender' => 2,
                'email' => 'companyuser+14@itpropartners.jp',
                'password' => bcrypt('admin14'),
                'avatar_path' => 'clients/14/avatar_path/SFkTQY7QBkRcoa4r7TUvBJcIvypf3h90j5oIS7Z5.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => '4',
                'first_name' => '恵利',
                'last_name' => '早川',
                'first_name_kana' => 'エリ',
                'last_name_kana' => 'ハヤカワ',
                'gender' => 2,
                'email' => 'companyuser+15@itpropartners.jp',
                'password' => bcrypt('admin15'),
                'avatar_path' => 'clients/15/avatar_path/34Z6j4g8ukFV4gCga8kTmRbBsjaNERWJPEI3HV3o.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
