<?php

use Illuminate\Database\Seeder;

class CompaniesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::table('companies')->truncate();
        DB::table('companies')->insert([
            [
                'name' => 'hajimari',
                'logo_path' => 'company/1/logo_path/LVfP52A6SrMtyDpZwXN72UEQOlwv7ub5nll2wdVC.png',
                'president_first_name' => '直人',
                'president_last_name' => '木村',
                'president_first_name_kana' => 'ナオト',
                'president_last_name_kana' => 'キムラ',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '1500043',
                'tel' => '03-6450-6076',
                'website' => 'https://www.hajimari.inc/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ITプロパートナーズ',
                'logo_path' => 'company/2/logo_path/clHZR7GdQFCtx8GJyq4IfxDQ7HrVPfipWoKqB8ue.png',
                'president_first_name' => '丈一郎',
                'president_last_name' => '岡安',
                'president_first_name_kana' => 'ジョウイチロウ',
                'president_last_name_kana' => 'オカヤス',
                'region_id' => 13,
                'address1' => '中央区銀座2-7-17',
                'address2' => '銀座ビル6階',
                'postcode' => '1040061',
                'tel' => '03-6277-5980',
                'website' => 'https://itpropartners.jp/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '株式会社ABC',
                'logo_path' => 'company/3/logo_path/O4UhFaeHHReztbI2VcYQJfrkDL4oYaA8CFnw4rr1.png',
                'president_first_name' => '明宏',
                'president_last_name' => '松田',
                'president_first_name_kana' => 'アキヒロ',
                'president_last_name_kana' => 'マツダ',
                'region_id' => 13,
                'address1' => '千代田区飯田橋２丁目３−１',
                'address2' => 'フジビル01',
                'postcode' => '1020072',
                'tel' => '03-6450-6077',
                'website' => 'https://www.abc.inc/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '株式会社Aidem',
                'logo_path' => 'company/4/logo_path/u02xHtx0IdRufztaMl4Bxi03bstPkqj19MvQiCcY.png',
                'president_first_name' => '和樹',
                'president_last_name' => '中村',
                'president_first_name_kana' => 'カズキ',
                'president_last_name_kana' => 'ナカムラ',
                'region_id' => 13,
                'address1' => '新宿区百人町1-13-1',
                'address2' => 'ベイ新宿ビル4階',
                'postcode' => '1690073',
                'tel' => '03-6450-6076',
                'website' => 'https://www.aidem.inc/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '株式会社LifeStyle',
                'logo_path' => 'company/5/logo_path/mYdYIpWnSWHrKcOXTaHIeWpUbltstUW8cQVfNL7G.png',
                'president_first_name' => '俊',
                'president_last_name' => '田中',
                'president_first_name_kana' => 'シュン',
                'president_last_name_kana' => 'タナカ',
                'region_id' => 13,
                'address1' => '千代田区麹町4-4-7',
                'address2' => '麹町タワー6階',
                'postcode' => '1020083',
                'tel' => '03-6277-5980',
                'website' => 'https://www.lifestyle.inc/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '株式会社Lang',
                'logo_path' => 'company/6/logo_path/moAlBZlZ3Z9SRAxwBsce3w3hsvDWsQHGgDucEjeM.png',
                'president_first_name' => '雄大',
                'president_last_name' => '山口',
                'president_first_name_kana' => 'ユウダイ',
                'president_last_name_kana' => 'ヤマグチ',
                'region_id' => 13,
                'address1' => '渋谷区代々木１−５５−１４',
                'address2' => '内海ビル201',
                'postcode' => '1510053',
                'tel' => '03-6450-6077',
                'website' => 'https://www.lang.inc/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '株式会社Clue',
                'logo_path' => 'company/7/logo_path/0Z5hkZ6LcgFohv9AvA2NDfNWaaq0yh1yR3HlS8Ok.png',
                'president_first_name' => '楓',
                'president_last_name' => '関',
                'president_first_name_kana' => 'カエデ',
                'president_last_name_kana' => 'セキ',
                'region_id' => 13,
                'address1' => '千代田区神田小川町1－1－16',
                'address2' => '山甚ビル6F',
                'postcode' => '1010052',
                'tel' => '03-6450-6076',
                'website' => 'https://www.clue.inc/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '株式会社ピア',
                'logo_path' => 'company/8/logo_path/K5V7rJhXK3D7cmkdefpuIXktgU2UzPza845L95QS.png',
                'president_first_name' => '隆治',
                'president_last_name' => '佐々木',
                'president_first_name_kana' => 'リュウジ',
                'president_last_name_kana' => 'ササキ',
                'region_id' => 13,
                'address1' => '武蔵野市吉祥寺南町1-9-9',
                'address2' => ' 吉祥寺ビル',
                'postcode' => '1800003',
                'tel' => '03-6277-5980',
                'website' => 'https://www.pia.inc/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '株式会社Erevista',
                'logo_path' => 'company/9/logo_path/x25YoCfO8hmrqjKizLxZOUUG3tryydQasaz1A9Om.png',
                'president_first_name' => '大樹',
                'president_last_name' => '石川',
                'president_first_name_kana' => 'ダイキ',
                'president_last_name_kana' => 'イシカワ',
                'region_id' => 13,
                'address1' => '新宿区四谷2-4-1',
                'address2' => '四谷ビル6F',
                'postcode' => '1600004',
                'tel' => '03-6450-6077',
                'website' => 'https://www.erevista.inc/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '株式会社トリピア',
                'logo_path' => 'company/10/logo_path/BSXuNLrgA1tKkIXiJSXSLu8iEqAq5pA2oBpKniJf.png',
                'president_first_name' => '秀樹',
                'president_last_name' => '草野',
                'president_first_name_kana' => 'ヒデキ',
                'president_last_name_kana' => 'クサノ',
                'region_id' => 13,
                'address1' => '港区芝5-31-17',
                'address2' => '田町ビル 6F',
                'postcode' => '1080014',
                'tel' => '03-6450-6076',
                'website' => 'https://www.toripia.inc/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '株式会社Tonight',
                'logo_path' => 'company/11/logo_path/FROxUO3LmT0WPDWMEygq2nOmOsIscHOMBaa23v9w.png',
                'president_first_name' => '大輝',
                'president_last_name' => '小川',
                'president_first_name_kana' => 'タイキ',
                'president_last_name_kana' => 'オガワ',
                'region_id' => 13,
                'address1' => '中央区京橋3丁目1-1',
                'address2' => '東京スクエア12階',
                'postcode' => '1040031',
                'tel' => '03-6277-5980',
                'website' => 'https://www.tonight.inc/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
