<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::table('users')->truncate();
        DB::table('users')->insert([
            [
                'first_name' => '一郎',
                'last_name' => '鈴木',
                'first_name_kana' => 'イチロウ',
                'last_name_kana' => 'スズキ',
                'gender' => 1,
                'email' => 'user+1@itpropartners.jp',
                'password' => bcrypt('admin'),
                'avatar_path' => 'users/1/avatar_path/nKAVdzbqJsfj4rkN4Bbc453FzLpHclny3s1QFyLA.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '涼介',
                'last_name' => '井上',
                'first_name_kana' => 'リョウスケ',
                'last_name_kana' => 'イノウエ',
                'gender' => 1,
                'email' => 'user+2@itpropartners.jp',
                'password' => bcrypt('admin2'),
                'avatar_path' => 'users/2/avatar_path/To8MtwIMexbb6NrXx0KLyHdAeM6jZbbFxdskYm9V.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '春香',
                'last_name' => '坂本',
                'first_name_kana' => 'ハルカ',
                'last_name_kana' => 'サカモト',
                'gender' => 2,
                'email' => 'user+3@itpropartners.jp',
                'password' => bcrypt('admin3'),
                'avatar_path' => 'users/3/avatar_path/rEbpEHxdgPHWjXcsAQ6fUVVQBnSQd8W2BXTVfYAv.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '太郎',
                'last_name' => '田中',
                'first_name_kana' => 'タロウ',
                'last_name_kana' => 'タナカ',
                'gender' => 1,
                'email' => 'user+4@itpropartners.jp',
                'password' => bcrypt('admin4'),
                'avatar_path' => 'users/4/avatar_path/ODEXXKqtln10A4ovV0i8oWGDzUaBXgoMJtbr7mKr.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '沙友理',
                'last_name' => '伊藤',
                'first_name_kana' => 'サユリ',
                'last_name_kana' => 'イトウ',
                'gender' => 2,
                'email' => 'user+5@itpropartners.jp',
                'password' => bcrypt('admin5'),
                'avatar_path' => 'users/5/avatar_path/TEPh6qqWnny2LtMYu9NkySm4e2gH1VNZv30YlhEi.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '舞',
                'last_name' => '渚',
                'first_name_kana' => 'マイ',
                'last_name_kana' => 'ナギサ',
                'gender' => 2,
                'email' => 'user+6@itpropartners.jp',
                'password' => bcrypt('admin6'),
                'avatar_path' => 'users/6/avatar_path/cF0QFH1ccLi9JBmR6GcMPKaKIvkD93qRlCtNvMxR.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '太一',
                'last_name' => '岡本',
                'first_name_kana' => 'タイチ',
                'last_name_kana' => 'オカモト',
                'gender' => 1,
                'email' => 'user+7@itpropartners.jp',
                'password' => bcrypt('admin7'),
                'avatar_path' => 'users/7/avatar_path/8YdO9QHkCfY4KqzekSLtMbLik2KMArDQnyMZrMef.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '雅也',
                'last_name' => '田口',
                'first_name_kana' => 'マサヤ',
                'last_name_kana' => 'タグチ',
                'gender' => 1,
                'email' => 'user+8@itpropartners.jp',
                'password' => bcrypt('admin8'),
                'avatar_path' => 'users/8/avatar_path/t8OhtwK4TZ84e6lpFDWjSdIlGm5aYNITbQTPb1Rz.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '由美子',
                'last_name' => '山口',
                'first_name_kana' => 'ユミコ',
                'last_name_kana' => 'ヤマグチ',
                'gender' => 2,
                'email' => 'user+9@itpropartners.jp',
                'password' => bcrypt('admin9'),
                'avatar_path' => 'users/9/avatar_path/OuXqCERd1D0d9pRV03pTWeIrzFbfUSWyPb3q8baM.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '健太郎',
                'last_name' => '吉田',
                'first_name_kana' => 'ケンタロウ',
                'last_name_kana' => 'ヨシダ',
                'gender' => 1,
                'email' => 'user+10@itpropartners.jp',
                'password' => bcrypt('admin10'),
                'avatar_path' => 'users/10/avatar_path/ydgJJefFJWeCtGKccPsWx6HS96GL7R8P5xNCKWLn.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '優香',
                'last_name' => '水野',
                'first_name_kana' => 'ユウカ',
                'last_name_kana' => 'ミズノ',
                'gender' => 2,
                'email' => 'user+11@itpropartners.jp',
                'password' => bcrypt('admin11'),
                'avatar_path' => 'users/11/avatar_path/FX8f9onprzETljujcffmGTByTOn9YIx7QnWa46aW.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '隆',
                'last_name' => '伊藤',
                'first_name_kana' => 'タカシ',
                'last_name_kana' => 'イトウ',
                'gender' => 1,
                'email' => 'user+12@itpropartners.jp',
                'password' => bcrypt('admin12'),
                'avatar_path' => 'users/12/avatar_path/2sN1wZFxkUWyD5OVSs99ZNfGkVJ7PRt4g80MrLbl.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '里奈',
                'last_name' => '吉川',
                'first_name_kana' => 'リナ',
                'last_name_kana' => 'ヨシカワ',
                'gender' => 2,
                'email' => 'user+13@itpropartners.jp',
                'password' => bcrypt('admin13'),
                'avatar_path' => 'users/13/avatar_path/QEkIQcu9YxGkoLSrrQAuNtgEbUkP0AqlCtbsUC7U.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '健',
                'last_name' => '佐々木',
                'first_name_kana' => 'タケル',
                'last_name_kana' => 'ササキ',
                'gender' => 1,
                'email' => 'user+14@itpropartners.jp',
                'password' => bcrypt('admin14'),
                'avatar_path' => 'users/14/avatar_path/81xVpdrUJ4vMtemGN7KJCsn07ksD5XAWhnnNm2Z7.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => '愛',
                'last_name' => '竹中',
                'first_name_kana' => 'アイ',
                'last_name_kana' => 'タケナカ',
                'gender' => 2,
                'email' => 'user+15@itpropartners.jp',
                'password' => bcrypt('admin15'),
                'avatar_path' => 'users/15/avatar_path/9sq43ynTk4kADh7nLx7Da0XbUwJPlV1aO1ThCGwp.png',
                'region_id' => 13,
                'address1' => '渋谷区道玄坂1-16-10',
                'address2' => '渋谷DTビル6階(総合受付)・8階',
                'postcode' => '150-0043',
                'tel' => '090-0000-0000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
